= Zeiterfassung für Gruppe 17

Notieren Sie die Zeit in Minuten für jeden Entwickler und – getrennt davon – für Team-Treffen pro Woche (Wochengranularität).
Die individuell erfasste Zeit beinhaltet auch das Lesen von Dokumentationen, Besprechungen mit Teamkollegen und sonstige auf das Praktikum bezogene Aufgaben, jedoch *nicht* das Team-Treffen (= letzte Spalte).

// See http://asciidoctor.org/docs/user-manual/#tables
[option="headers"]
|===
|Woche |David Schroth |Marc Albrecht |Sebastian Jaster |Edgar Wolfert |Johannes Kaufmann |Shintaro Onogi |Meeting
|1  |300   |400    |610    |270    |540    |180    |40
|2  |540   |600    |1015   |600    |690    |300    |90
|3  |900   |1000   |1090   |800    |850    |800    |75
|4  |720   |1000   |1100   |900    |700    |500    |30
|5  |400   |700    |1350   |720    |600    |500    |50
|6  |480   |1000   |1050   |600    |630    |500    |30
|7  |630   |1000   |1235   |700    |700    |500    |60
|8  |300   |1200   |1075   |240    |300    |360    |120 
|9  |280   |700    |655    |300    |300    |240    |45    
|10  |…   |800    |480    |400    |…    |180    |…    
|11  |…   |…    |…    |…    |…    |…    |…    
|12  |…   |…    |…    |…    |…    |…    |…    
|===

Bitte tragen Sie am Ende des Praktikums noch folgende weitere Werte ein:
Summe der Arbeitsstunden pro Student:

SUMME(SPALTE(DevX))

Arbeitsstunden pro Woche pro Student:

SUMME(SPALTE(DevX)) / 12

Durchschnittliche Arbeitzeit aller Studenten pro Woche:

(SUMME(SPALTE(Dev1)) + SUMME(SPALTE(Dev2)) + SUMME(SPALTE(Dev3)) + SUMME(SPALTE(Dev4)) + SUMME(SPALTE(Dev5)) +SUMME(SPALTE(Dev6))) / 6
